OPENAI_API_KEY="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"
OPENAI_MODEL = "gpt-3.5-turbo"

NEO4J_URI = "bolt://54.85.193.219:7687"
NEO4J_USERNAME = "neo4j"
NEO4J_PASSWORD = "groan-ore-insanity"

ASTRADB_ID="nusrvtqgouAoNEBfiJgEKQAc"
ASTRADB_SECRET=",Xr966W9sB._slt6wltRCOjxzSsfr3AZU7fQZTs7_.nI1rfW2XfMtYypq9PnzZvhw+OCY+yv-mFuiyQWh_GARhfvw0Z0MxwaA2sk6d9zm.8jWm-gAaHdE0CJALE_GENg"
